/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Game game = new Game();
        Main mainApp = new Main();
        mainApp.start(game);
    }

    private static final List<String> validMoves = Arrays.asList(
            "arriba izquierda", "arriba centro", "arriba derecha",
            "medio izquierda", "medio centro", "medio derecha",
            "abajo izquierda", "abajo centro", "abajo derecha"
    );

    public void start(Game game) {
        System.out.println("Bienvenido al juego de Tic-Tac-Toe!");
        Scanner scanner = new Scanner(System.in);

        while (true) {
            Board.displayBoard();
            String input = scanner.nextLine().trim().toLowerCase();  //Captura lo que el usuario escribiera y lo convierte en minus

            if (isValidCharacter(input)) {

                Board.playerMove(input);
                if (gameStatus(game)) {
                    game.endGame();
                    break;

                    Board.computerMove(input);
                    if (gameStatus(game)) {
                        System.out.println("¡El juego ha terminado!");
                        game.endGame();
                        break;
                    }
                } else {
                    System.out.println("Entrada no válida. Inténtelo de nuevo.");
                }
            }
            scanner.close();
        }

        public boolean gameStatus(Game game) {
            //Revisa si se gano o si se empeato
            return game.checkWin() || game.checkDraw();
        }

        public boolean isValidCharacter(String input) {
            return validMoves.contains(input);
        }
    }
